fix: add feature name and reference to raw.var
chanzuckerberg/single-cell-curation pull request #210
Opened 2022-03-30 22:50 UTC by seve

#203

2022-03-30 22:55 UTC, brianraymor commented
@jahilton should be able to provide you with a test dataset.

2022-03-31 18:07 UTC, seve commented on cellxgene_schema_cli/cellxgene_schema/write_labels.py
Could probably functionalize `.__dict__["_" + component]`, but not sure where to store that function

2022-03-31 18:45 UTC, MDunitz commented on cellxgene_schema_cli/cellxgene_schema/write_labels.py
>              # adata.__dict__["_obs"] is adata.obs
can you add a comment about doing the split to support var.raw

2022-03-31 18:45 UTC, MDunitz requested changes
lgtm with a small change

2022-03-31 19:11 UTC, seve commented
> @jahilton should be able to provide you with a test dataset.

Confirmed working with test dataset!

```
                    feature_type          ensemblid feature_biotype
gene_id
ENSG00000223972  Gene Expression  ENSG00000223972.5            gene
ENSG00000227232  Gene Expression  ENSG00000227232.5            gene
ENSG00000278267  Gene Expression  ENSG00000278267.1            gene
ENSG00000243485  Gene Expression  ENSG00000243485.5            gene
ENSG00000284332  Gene Expression  ENSG00000284332.1            gene
```

```
                    feature_type          ensemblid  ... feature_name feature_reference
gene_id                                              ...
ENSG00000223972  Gene Expression  ENSG00000223972.5  ...      DDX11L1    NCBITaxon:9606
ENSG00000227232  Gene Expression  ENSG00000227232.5  ...       WASH7P    NCBITaxon:9606
ENSG00000278267  Gene Expression  ENSG00000278267.1  ...    MIR6859-1    NCBITaxon:9606
ENSG00000243485  Gene Expression  ENSG00000243485.5  ...  MIR1302-2HG    NCBITaxon:9606
ENSG00000284332  Gene Expression  ENSG00000284332.1  ...    MIR1302-2    NCBITaxon:9606
```

2022-03-31 19:17 UTC, pablo-gar approved these changes
LGTM!

2022-03-31 20:08 UTC, merged