feat: add suspension_type
chanzuckerberg/single-cell-curation pull request #322
Opened 2022-08-10 19:06 UTC by nayib-jose-gloria

#273 

Notes for Reviewers: 
- Please opine on warning message 
- Please opine on newly introduced yaml headings (warning_message, complex_rule and its subfields, etc.)
- I separated all the rules to be able to provide specific error messages, but let me know if you think it would be a cleaner pattern to group the 'cell'-only, 'nucleus'-only, 'na' only, 'cell' or 'nucleus' rules into groups and give more generic messages (i.e. something like 'ERROR: assay in [list of rule group assays] found to have invalid suspension type')

2022-08-10 19:11 UTC, nayib-jose-gloria commented on cellxgene_schema_cli/cellxgene_schema/validate.py
> +                continue
I added this else: continue with the idea of not breaking if we add another subcase in the future but I can remove if its too confusing

2022-08-10 19:11 UTC, nayib-jose-gloria commented on cellxgene_schema_cli/tests/fixtures/examples_validate.py
> +            "EFO:0009918",
changed because previous example was not a valid EFO for suspension_type, would add warnings to all the test outputs

2022-08-11 17:53 UTC, ebezzi approved these changes

2022-08-11 20:35 UTC, pablo-gar requested changes

2022-08-11 20:35 UTC, pablo-gar commented on cellxgene_schema_cli/cellxgene_schema/validate.py
> +                    query_exp = f"@filter_df_by_ancestor_match({rule_def['column']}, {ontology_keys}, {ancestor_list})"
Can you encapsulate this in a separate function for readability?

2022-08-12 19:03 UTC, merged