feat(): Add version tracking for Gencode releases
chanzuckerberg/single-cell-curation pull request #436
Opened 2023-05-09 18:21 UTC by Bento007

2023-05-10 16:06 UTC, nayib-jose-gloria commented on cellxgene_schema_cli/cellxgene_schema/ontology_files/gene_info.md
> +This file describes the expected format of *[gene_info.yml](./gene_info.yml)*. It is used to track is used to track the
accidentally duplicated start of sentence

2023-05-10 16:13 UTC, nayib-jose-gloria requested changes
It looks like the GHA workflow file to run this job was deleted in the latest commit--was that a mistake?

2023-05-10 16:21 UTC, Bento007 commented
That we me trying to clean up my git history.

2023-05-10 16:29 UTC, nayib-jose-gloria commented on .github/workflows/gene_update.yml
> +          git push
Same note as the other PR--push tests don't run in the PR after this commit, which could hide failing tests

2023-05-10 16:57 UTC, nayib-jose-gloria reviewed
Changes look good! Just missing a step to re-run tests after auto-commit

2023-05-11 13:04 UTC, nayib-jose-gloria reviewed
very nit: I'm thinking we should rename push tests, since we're doing more than just testing. push_automation? push_jobs?

2023-05-11 18:30 UTC, nayib-jose-gloria approved these changes

2023-05-11 20:01 UTC, merged