fix: throw error if obsm is not type np.ndarray
chanzuckerberg/single-cell-curation pull request #859
Opened 2024-04-25 23:09 UTC by Bento007

## Reason for Change

- #857

## Changes

- change warning to an error when obsm field is not type numpy.ndarray.

## Testing

- Update the unit tests to match expect behavior

2024-04-26 16:47 UTC, nayib-jose-gloria commented on cellxgene_schema_cli/tests/test_schema_compliance.py
> +            "WARNING: All embeddings have to be of 'numpy.ndarray' type, 'adata.obsm['harmony']' is <class 'pandas.core.frame.DataFrame'>')."
nit: we should be consistent and append errors with ERROR (blocks validation) rather than WARNING (doesn't)

2024-04-30 03:02 UTC, MillenniumFalconMechanic approved these changes

2024-04-30 13:48 UTC, nayib-jose-gloria reviewed
Change looks good for ndarray check, but I think we're missing validation for the rest of this rule:

> The value for each str key MUST be a numpy.ndarray **of shape (n_obs, m), where n_obs is the number of rows in X and m >= 1.**

We throw a warning if a non-spatial, non-X-prefix embedding value has a row count != n_obs--that should become an error as well. And I don't think we check for column count >= 1 at all; we warn on column count < 2 (and error for spatial / X-prefix embedding keys)

2024-04-30 13:49 UTC, nayib-jose-gloria requested changes
Change looks good for ndarray check, but I think we're missing validation for the rest of this rule:

> The value for each str key MUST be a numpy.ndarray **of shape (n_obs, m), where n_obs is the number of rows in X and m >= 1.**

We throw a warning if a non-spatial, non-X-prefix embedding value has a row count != n_obs--that should become an error as well. And I don't think we check for column count >= 1 at all; we warn on column count < 2 (and error for spatial / X-prefix embedding keys)

2024-05-02 21:51 UTC, nayib-jose-gloria commented on cellxgene_schema_cli/cellxgene_schema/validate.py
> +                    f"All embeddings must at least two dimensions. 'adata.obsm['{key}']' has a shape length of '{len(value.shape)}'."
nit: I think it must be exactly two dimensions

2024-05-02 21:54 UTC, nayib-jose-gloria commented on cellxgene_schema_cli/cellxgene_schema/validate.py
> +                        f"All other embeddings must have at least one column. 'adata.obsm['{key}']' has columns='{value.shape[1]}'."
nit: in this context, I don't think the curator reading would know what "other embeddings" mean. Maybe "any embeddings not specified in the schema reference"?

2024-05-02 22:04 UTC, nayib-jose-gloria approved these changes
1 nit about wording on an error statement but otherwise looks good. Ready for product review after that

2024-05-03 13:35 UTC, nayib-jose-gloria commented
@brian-mott ready for review!

2024-05-03 17:20 UTC, brian-mott approved these changes
Looks good, thanks Trent and Nayib!

2024-05-06 16:22 UTC, merged